# Generated by Django 5.0.4 on 2024-05-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_boost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boost',
            name='lvl',
        ),
        migrations.AddField(
            model_name='boost',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boost',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'casual'), (1, 'auto')], default=0),
        ),
        migrations.AddField(
            model_name='core',
            name='auto_click_power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='core',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
